# Generated by Django 4.2.23 on 2025-06-23 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeliculaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('show_id', models.IntegerField()),
                ('imagen_url', models.URLField(blank=True)),
                ('resumen', models.TextField(blank=True)),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LibroFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(blank=True, max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('portada_url', models.URLField(blank=True)),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
