# Generated by Django 4.2.23 on 2025-06-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_peliculafavorita_librofavorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(blank=True, max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('portada_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('show_id', models.IntegerField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True)),
            ],
        ),
    ]
